# Generated by Django 4.2.5 on 2023-09-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=None, null=True,
                                       verbose_name='ending date'),
        ),
    ]
